name: calculator_app
description: Calculator - Caster.IO project to showcase testing techniques
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  calculator:
    path: packages/calculator
  material_segmented_control: 2.1.0+1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.16.6
  mockito: ^5.0.0


flutter:
  uses-material-design: true
