name: calculator_app_test

on: pull_request

jobs:
  tests:
    runs-on:
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - name: install dependencies
        run: flutter packages get
      - name: run tests
        run: flutter test --exclude-tags='no-ci'  